[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spectrum-builder"
version = "1.0.1"
requires-python = ">=3.9"
dependencies = ["numpy", "pandas", "matplotlib", "streamlit"]

[tool.setuptools.packages.find]
include = ["spectrum_builder*"]
